# Override Docker dependencies to avoid installing python3-debian on Ubuntu
docker_dependencies: ["apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release", "software-properties-common", "python3", "python3-pip", "python3-venv", "sudo", "git"]
